In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3615, 8364, 4393, 1413],
 [3615, 8364, 4393, 3914],
 [3615, 3758, 4393, 8368],
 [8919, 1995, 4050, 496, 734],
 [8919, 1995, 4050, 496, 5114],
 [4153, 3615, 5287, 4393, 7274],
 [7289, 1949, 8490, 496]]

In [24]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3615 8364 4393 1413]
 [   0    0    0    0 3615 8364 4393 3914]
 [   0    0    0    0 3615 3758 4393 8368]
 [   0    0    0 8919 1995 4050  496  734]
 [   0    0    0 8919 1995 4050  496 5114]
 [   0    0    0 4153 3615 5287 4393 7274]
 [   0    0    0    0 7289 1949 8490  496]]


In [27]:
## feature representation
dim=10

In [28]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile(optimizer='adam', loss='mse')

In [29]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 596ms/step


array([[[-7.0958212e-04,  2.0878579e-02, -4.8223354e-02,  1.3531987e-02,
         -3.4954727e-02, -3.9318491e-02, -3.4238480e-02,  4.8722055e-02,
         -3.7101842e-02, -4.7789861e-02],
        [-7.0958212e-04,  2.0878579e-02, -4.8223354e-02,  1.3531987e-02,
         -3.4954727e-02, -3.9318491e-02, -3.4238480e-02,  4.8722055e-02,
         -3.7101842e-02, -4.7789861e-02],
        [-7.0958212e-04,  2.0878579e-02, -4.8223354e-02,  1.3531987e-02,
         -3.4954727e-02, -3.9318491e-02, -3.4238480e-02,  4.8722055e-02,
         -3.7101842e-02, -4.7789861e-02],
        [-7.0958212e-04,  2.0878579e-02, -4.8223354e-02,  1.3531987e-02,
         -3.4954727e-02, -3.9318491e-02, -3.4238480e-02,  4.8722055e-02,
         -3.7101842e-02, -4.7789861e-02],
        [-3.5726823e-02, -4.2828172e-04,  2.2408012e-02, -4.1077279e-02,
          7.9960227e-03, -2.5312066e-02, -2.1556914e-02, -9.6177571e-03,
          4.2589877e-02,  2.2148851e-02],
        [ 5.1741973e-03,  4.8529577e-02, -4.8956323e-02,  1.

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 3615, 8364, 4393, 1413])

In [32]:
# model.predict(embedded_docs[0])
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[-0.00070958,  0.02087858, -0.04822335,  0.01353199,
         -0.03495473, -0.03931849, -0.03423848,  0.04872205,
         -0.03710184, -0.04778986],
        [-0.00070958,  0.02087858, -0.04822335,  0.01353199,
         -0.03495473, -0.03931849, -0.03423848,  0.04872205,
         -0.03710184, -0.04778986],
        [-0.00070958,  0.02087858, -0.04822335,  0.01353199,
         -0.03495473, -0.03931849, -0.03423848,  0.04872205,
         -0.03710184, -0.04778986],
        [-0.00070958,  0.02087858, -0.04822335,  0.01353199,
         -0.03495473, -0.03931849, -0.03423848,  0.04872205,
         -0.03710184, -0.04778986],
        [-0.03572682, -0.00042828,  0.02240801, -0.04107728,
          0.00799602, -0.02531207, -0.02155691, -0.00961776,
          0.04258988,  0.02214885],
        [ 0.0051742 ,  0.04852958, -0.04895632,  0.01148571,
          0.02973659, -0.00301844, -0.0066672 , -0.02944173,
          0.04987797, -0.0059128 ],
        [ 0.04513503,  0.03572537, -0.02173749, -0.0