In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3615, 8364, 4393, 1413],
 [3615, 8364, 4393, 3914],
 [3615, 3758, 4393, 8368],
 [8919, 1995, 4050, 496, 734],
 [8919, 1995, 4050, 496, 5114],
 [4153, 3615, 5287, 4393, 7274],
 [7289, 1949, 8490, 496]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3615 8364 4393 1413]
 [   0    0    0    0 3615 8364 4393 3914]
 [   0    0    0    0 3615 3758 4393 8368]
 [   0    0    0 8919 1995 4050  496  734]
 [   0    0    0 8919 1995 4050  496 5114]
 [   0    0    0 4153 3615 5287 4393 7274]
 [   0    0    0    0 7289 1949 8490  496]]


In [10]:
## feature representation
dim=10

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile(optimizer='adam', loss='mse')

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step


array([[[-3.45295295e-02, -4.58634607e-02, -4.06306982e-02,
         -1.09991208e-02, -1.59950033e-02,  3.19373719e-02,
          1.90266259e-02,  8.15855339e-03,  8.43355805e-03,
          1.04742050e-02],
        [-3.45295295e-02, -4.58634607e-02, -4.06306982e-02,
         -1.09991208e-02, -1.59950033e-02,  3.19373719e-02,
          1.90266259e-02,  8.15855339e-03,  8.43355805e-03,
          1.04742050e-02],
        [-3.45295295e-02, -4.58634607e-02, -4.06306982e-02,
         -1.09991208e-02, -1.59950033e-02,  3.19373719e-02,
          1.90266259e-02,  8.15855339e-03,  8.43355805e-03,
          1.04742050e-02],
        [-3.45295295e-02, -4.58634607e-02, -4.06306982e-02,
         -1.09991208e-02, -1.59950033e-02,  3.19373719e-02,
          1.90266259e-02,  8.15855339e-03,  8.43355805e-03,
          1.04742050e-02],
        [ 4.01263312e-03,  3.43770273e-02,  1.58375166e-02,
          7.21007586e-03,  1.55921467e-02,  4.66643609e-02,
          3.43411230e-02, -3.39838639e-02,  1.362860

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 3615, 8364, 4393, 1413])

In [17]:
# model.predict(embedded_docs[0])
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[[-0.03452953, -0.04586346, -0.0406307 , -0.01099912,
         -0.015995  ,  0.03193737,  0.01902663,  0.00815855,
          0.00843356,  0.01047421],
        [-0.03452953, -0.04586346, -0.0406307 , -0.01099912,
         -0.015995  ,  0.03193737,  0.01902663,  0.00815855,
          0.00843356,  0.01047421],
        [-0.03452953, -0.04586346, -0.0406307 , -0.01099912,
         -0.015995  ,  0.03193737,  0.01902663,  0.00815855,
          0.00843356,  0.01047421],
        [-0.03452953, -0.04586346, -0.0406307 , -0.01099912,
         -0.015995  ,  0.03193737,  0.01902663,  0.00815855,
          0.00843356,  0.01047421],
        [ 0.00401263,  0.03437703,  0.01583752,  0.00721008,
          0.01559215,  0.04666436,  0.03434112, -0.03398386,
          0.00136286, -0.00230382],
        [-0.03005214,  0.03741593,  0.02317044,  0.02897498,
          0.04447036, -0.00056875, -0.01187544,  0.00585537,
         -0.04963535, -0.0128575 ],
        [-0.00787791, -0.03457961,  0.04665661,  0.0